# Generated by Django 3.1.2 on 2020-10-19 14:56

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=222)),
                ('email', models.CharField(blank=True, max_length=222)),
                ('subject', models.TextField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('Yangi', 'Yangi'), ("O'qildi", "O'qildi"), ('Yopilgan', 'Yopilgam')], default='Yangi', max_length=10)),
                ('ip', models.CharField(blank=True, max_length=155)),
                ('note', models.CharField(blank=True, max_length=155)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=222)),
                ('keywords', models.CharField(max_length=222)),
                ('description', models.TextField(max_length=255)),
                ('company', models.CharField(max_length=150)),
                ('address', models.CharField(blank=True, max_length=155)),
                ('phone', models.CharField(blank=True, max_length=155)),
                ('fax', models.CharField(blank=True, max_length=155)),
                ('email', models.CharField(blank=True, max_length=155)),
                ('icon', models.ImageField(blank=True, upload_to='images/')),
                ('facebook', models.CharField(blank=True, max_length=155)),
                ('instagram', models.CharField(blank=True, max_length=155)),
                ('twitter', models.CharField(blank=True, max_length=155)),
                ('youtube', models.CharField(blank=True, max_length=155)),
                ('aboutus', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('contact', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('references', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'setting',
                'verbose_name_plural': 'settings',
            },
        ),
    ]
