# Generated by Django 3.1.2 on 2020-10-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, choices=[('Tashkent', 'Tashkent'), ('Andijon', 'Andijon'), ('Jizzah', 'Jizzah'), ('Xorazm', 'Xorazm')], max_length=20),
        ),
    ]
